
      


      
      

server:
  port: 8090

spring:  
  sql:
    init:
      platform: h2 
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none