server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project2
    username: root
    password: root
  logging:
    level:
      com:
        skillstorm: WARN  
  application:
    name: skillstorm-api
  jpa:
    # please use Pascal_Case so you don't need this:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none