/*******************************************************************************
   Create Dummies
********************************************************************************/

insert into Status (Name) values ('Free Trial');
insert into Status (Name) values ('Active');
insert into Status (Name) values ('Expiring Soon');
insert into Status (Name) values ('Inactive');

insert into Intervals (Name, Duration) values ('7 day free trial', 7);
insert into Intervals (Name, Duration) values ('1 month', 31);
insert into Intervals (Name, Duration) values ('3 months', 93);
insert into Intervals (Name, Duration) values ('6 months', 186);

INSERT INTO ServicePlan (Name,Price) VALUES ('Free','$0.00');
INSERT INTO ServicePlan (Name,Price) VALUES ('Standard','$9.99');
INSERT INTO ServicePlan (Name,Price) VALUES ('Plus','$14.99');
INSERT INTO ServicePlan (Name,Price) VALUES ('Premium','$19.99');


INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Ned','Gonnard','ngonnard0','ngonnard0@washingtonpost.com','$2a$12$60l6AGOuUsm15pKSFrTiOeWfX3tym0Dq0RHDN1EM5qjsbpr8Xl9SK',NULL,NULL,'8/14/2022',2,2,2);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Fulvia','Parsley','fparsley1','fparsley1@indiatimes.com','$2a$12$3HASbZdar58IXn9.L5FqnuYnQKczvjZkZmlUBu8DaCscQhxJDMz96',NULL,NULL,NULL,1,1,1);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Jean','Zelner','jzelner2','jzelner2@forbes.com','$2a$12$PxVYgg6n38Nqwu5nm.l4FOiQ7nSoRhiBp3/URndn6PwBeVw0cr3bm',NULL,NULL,NULL,1,1,1);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Curcio','Redmayne','credmayne3','credmayne3@fda.gov','$2a$12$PB0YVKnWbHGGHik6ej0L2OYYz0g1eRj6a.G1pa59Yjey2oDH0rs1m',NULL,NULL,NULL,3,4,2);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Arin','Pepperell','apepperell4','apepperell4@tripod.com','$2a$12$sDEAGCUK5tlvdqVZWVee4OR9cyYShh/KS8teg9v9mG22wY6hPrQBy',NULL,NULL,NULL,1,1,1);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Tiebout','Stanbury','tstanbury5','tstanbury5@reddit.com','$2a$12$pdPstjr8g.H5dhxqSFIdFu38f6bLd0ekb6Teuyw731.pbfMbmnLJa',NULL,NULL,NULL,2,2,2);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Herculie','Naulls','hnaulls6','hnaulls6@yellowpages.com','$2a$12$osDgmH7Nh6QS3Th/XZebEOGXhOKuFtvT2hLNvx64gZjLHl4Xq2rDu',NULL,NULL,NULL,3,2,2);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Rube','Aslie','raslie7','raslie7@soup.io','$2a$12$6dbLwoTUfwvxhftgCWzLYuAHJqEGstWigvTt8vQqBM.RPLj0SqdRy',NULL,NULL,NULL,2,3,3);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Elliott','Bugbee','ebugbee8','ebugbee8@marketwatch.com','$2a$12$LEQLl/n32EFmCo1bZaHxjuqXcXvSImg7zGTDAUx9/mI89OpJ1HAeS',NULL,NULL,NULL,4,4,3);
INSERT INTO Profile (FirstName,LastName,Username,Email,Password,StartDate,NextBillDate,EndDate,StatusId,IntervalsId,ServicePlanId) VALUES ('Lucais','de Castelain','ldecastelain9','ldecastelain9@devhub.com','$2a$12$bdmuZL2g2x2ClQUbZo6koO49ps9p3mmcIxtZv7RU7VwwlZ8QTyPf6',NULL,NULL,NULL,2,2,4);


INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/01/2021',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/01/2021',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('08/01/2022',1);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/08/2022',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/20/2021',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/13/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/09/2021',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/21/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/04/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/22/2022',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/24/2021',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/23/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/31/2022',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/29/2022',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('08/07/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/18/2022',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/13/2022',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/25/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/26/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/25/2021',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/15/2022',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/31/2021',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/12/2022',10);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/04/2022',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/02/2021',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/28/2022',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/21/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/25/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/18/2022',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/22/2022',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/02/2022',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/16/2021',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/24/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/25/2021',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/16/2021',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/15/2021',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/01/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/15/2021',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/29/2022',10);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/16/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/16/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/31/2022',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/15/2021',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/14/2022',10);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/02/2021',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/12/2022',10);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/19/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/04/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('08/07/2022',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/05/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('08/01/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/26/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/20/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/18/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/04/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/27/2021',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/27/2022',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/15/2022',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/12/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/31/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/02/2021',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/14/2022',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/26/2022',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/22/2021',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('02/28/2022',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/28/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/18/2021',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/30/2022',10);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/26/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/24/2022',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/25/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/09/2022',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/10/2022',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('05/10/2022',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/01/2022',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/26/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/18/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('11/16/2021',10);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/17/2021',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('10/20/2021',2);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/24/2021',4);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/02/2022',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/26/2021',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/26/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('06/13/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('07/08/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/13/2022',7);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/31/2022',3);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('01/15/2022',5);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/10/2022',8);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('12/19/2021',9);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('03/22/2022',6);
INSERT INTO BillingInformation (BilledOnDate,ProfileId) VALUES ('04/15/2022',10);
